#!/usr/bin/env bash

###############################################################################
# Script Initialization                                                       #
###############################################################################

# Detect architecture "32" or "64"
ARCH=$(uname -m | sed 's/x86_//;s/i[3-6]86/32/')
# Set an architecture boolean
IS_X64=$(( ${ARCH} == "64" ))

# Simple function for downloading and installing a deb package
function download_and_install() {
    # Download the artifact
    wget -O pkg.deb $1
    # Install the package
    yes | sudo dpkg -i pkg.deb
    # Resolve dependencies
    sudo apt-get -f install -y
    # Remove the artifact
    rm pkg.deb
}

###############################################################################
# Install regulare packages and PPAs                                         #
###############################################################################

# Ensure that we have the necessary tools for setting up new PPAs
sudo apt-get install -y software-properties-common

# Auto accept the mscorefonts eula (during apt-get installation)
echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections

# Update the package list
sudo apt-get update

# List of apt packages to get
PACKAGES=(
    ffmpeg
    git
    git-lfs
    gnupg
    imagemagick
    jq
    markdown
    npm
    python2
    python2-dev
    python3
    python3-dev
    python-is-python3
    build-essential
    ruby
    rubygems-integration
    openssh-client
    openssh-server
    synaptic
    whois
    rar
    htop
    curl
    geeqie
    chromium-browser
    openjdk-8-jdk
    openjdk-8-jre
    openjdk-11-jdk
    openjdk-11-jre
    firefox
    vlc
    gimp
    filezilla
    keepassxc
    qbittorrent
    virtualbox
    virtualbox-qt
    virtualbox-guest-additions-iso
    git-cola
    unrar-free
    p7zip-full
    xdotool
)

echo "Append distribution specific apt packages"
if [ $DISTRIBUTION == "ubuntu" ]; then
    UBUNTU_PACKAGES=(
        nautilus-dropbox
        ubuntu-restricted-extras
    )
    PACKAGES=("${PACKAGES[@]}" "${UBUNTU_PACKAGES[@]}")
elif [ $DISTRIBUTION == "linuxmint" ]; then
    MINT_PACKAGES=(
        ia32-libs
        nemo-dropbox
    )
    PACKAGES=("${PACKAGES[@]}" "${MINT_PACKAGES[@]}")
fi

echo "Installing packages... ${PACKAGES[@]}"
sudo apt-get install -y ${PACKAGES[@]}

echo "Cleaning up..."
sudo apt-get clean

###############################################################################
# Install regulare packages and PPAs                                         #
###############################################################################

echo "Installing Sublime text..."
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt-get update
sudo apt-get install -y sublime-text

echo "Installing Intellij..."
sudo add-apt-repository -y ppa:mmk2410/intellij-idea
sudo apt-get update
sudo apt-get install -y intellij-idea-community

echo "Installing TeamViewer..."
if [ $IS_X64 ]; then
    download_and_install 'https://download.teamviewer.com/download/linux/teamviewer_amd64.deb'
else
    download_and_install 'https://download.teamviewer.com/download/linux/teamviewer_i386.deb'
fi

echo "Installing FileBot..."
if [ $IS_X64 ]; then
    download_and_install 'http://filebot.sourceforge.net/download.php?type=deb&arch=amd64'
else
    download_and_install 'http://filebot.sourceforge.net/download.php?type=deb&arch=i386'
fi

echo "Installing Signal..."
wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg
cat signal-desktop-keyring.gpg | sudo tee -a /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null
echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main' | sudo tee -a /etc/apt/sources.list.d/signal-xenial.list
sudo apt update && sudo apt install -y signal-desktop

echo "Installing Telegram..."
wget -O telegram.tar.xz https://telegram.org/dl/desktop/linux
tar xf telegram.tar.xz
sudo mv Telegram /opt/telegram
sudo ln -sf /opt/telegram/Telegram /usr/bin/telegram
rm telegram.tar.xz

echo "Installing VSCode..."
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/packages.microsoft.gpg > /dev/null
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | sudo tee /etc/apt/sources.list.d/vscode.list
sudo apt update
sudo apt install code -y

echo "Applying debian system preferences"

###############################################################################
# General UI/UX                                                               #
###############################################################################

###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
###############################################################################

###############################################################################
# Android                                                                     #
###############################################################################

# Device udev rules
sudo curl --create-dirs -L -o /etc/udev/rules.d/51-android.rules -O -L https://raw.githubusercontent.com/snowdream/51-android/master/51-android.rules
sudo chmod a+r /etc/udev/rules.d/51-android.rules
sudo service udev restart

###############################################################################
# Dock, Dashboard, and hot corners                                            #
###############################################################################

###############################################################################
# Photos                                                                      #
###############################################################################

###############################################################################
# Kill affected applications                                                  #
###############################################################################

sudo apt-get autoremove -y

echo "Done. Note that some of these changes require a logout/restart to take effect."
